version: '3.3'

services:
  backend:
    build: ./backend/
    container_name: micro2_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/micro2
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FRONTEND_HOST=http://localhost
  frontend:
    container_name: micro2_frontend
    build: ./frontend/
    ports:
      - "80:80"
  db:
    image: 'postgres:13.1-alpine'
    container_name: micro2_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=micro2
    expose:
      - 5432
